### ISSUE TITLE
Saturate a QR Code Symbol of a given version and EC level

### ISSUE THREAD

**Issue by emanonv** [kennytm/qrcode-rust#3]
Hello, kennytm. I'm not sure this is the correct venue to raise this issue. I apologies in advance if expressing this issue here is not appropriate.

When encoding is done using `QrCode::with_version`, `push_optimal_data` is used internally to dynamically select the best encoding for the segmented data. This makes the maximum amount of data a QR-code symbol can hold dependent on the nature of the encoded data.

Is it possible to determine this amount using this crate's public API? If not, is it possible to oversupply data to the encoder and determine how much of that data was successfully encoded?

Background information: I am working on an open source project that serializes binary data as a series of QR Code symbols. I need to keep the number of generated symbols to a minimum. There are constants on symbol dimensions and module size; and hence the requirement for a version limit.

Any help would be greatly appreciated.

**Comment by kennytm** [comment]
Hi,

The maximum amount of bits for each Version + EcLevel is not exposed to public for now, but you could refer to the table in https://github.com/kennytm/qrcode-rust/blob/5e3a7ecc74c2bee118230743b798c75b1ba24e0c/src/bits.rs#L600-L649. The number of bits encoded can be tracked using `Bits::len()`, but it does not know if it has overflowed before pushing the terminator (as the EcLevel also affects how much data can be encoded).

If your data has fairly consistent encoding (e.g. all numbers), you could use http://www.qrcode.com/en/about/version.html to determine the upper bound for each symbol.

**Comment by emanonv** [comment]
Unfortunately, the data is not not constrained to numerals or alphanumerics , so the maximums mentioned on qrcode.com and in the standard do not apply (or rather, they'll lead to wasting usable capacity).

For now, I'm brute forcing the optimal encoding via binary search. I'll take a second look at this problem and try to write a function that calculates this value if I manage to find some free time. If it's well-written enough to warrant sharing, I'll submit it to you to freely accept or reject.

Thank you for taking the time to write out a detailed response.
