### ISSUE TITLE
docs.rs documentation failed

### ISSUE THREAD

**Issue by senden9** [kennytm/qrcode-rust#41]
The online documentation at https://docs.rs/crate/qrcode/ failed to build. The [logs](https://docs.rs/crate/qrcode/0.11.1/builds/207283) say something like ```error: `[0]` cannot be resolved, ignoring it```.

Local documentation build just fine with `qrcode = "0.11.1"`.

**Comment by kennytm** [comment]
Thanks for reporting. This is a problem with intra-docs support in Nightly.
