### ISSUE TITLE
Very likely bug in error correction constants

### ISSUE THREAD

**Issue by emanonv** [kennytm/qrcode-rust#7]
I've been experiencing a bug that only effects QR code version-27 with error correction set to Q; All other combinations don't seem effected.

I believe that the source of this bug is an incorrect value in the `DATA_BYTES_PER_BLOCK` for the combination. (see file `ec.rs`, line: `415`).

Table 9 of the standard states that the number of blocks should be 26 for `24` not 27.

Your input on this matter would be greatly appreciated.

Thank you.

**Comment by kennytm** [comment]
Fixed in fee9deda25a19f6b659a8fb14493d52473eba1f2. Thanks!
