### ISSUE TITLE
`svg::Color` can construct invalid color

### ISSUE THREAD

**Issue by sorairolake** [kennytm/qrcode-rust#72]
All [SVG 1.1 colors](https://www.w3.org/TR/SVG11/color.html) are specified in the sRGB color space, and are compatible with CSS2 colors. However, [`svg::Color`](https://docs.rs/qrcode/0.14.1/qrcode/render/svg/struct.Color.html) can accept any string, so invalid colors can be constructed:

```rust
use qrcode::render::svg::Color;

let ok = Color("#ffa500");
let err = Color("The quick brown fox jumps over the lazy dog.");
```

So I think it would be better to check for a valid value ​​when constructing `svg::Color` like this:

```rust
pub struct Color<'a>(&'a str);

impl<'a> Color<'a> {
    pub fn new(color: &'a str) -> Result<Self, Error> {
        ...
    }
}
```

Or, it would be better to construct it from a RGBA value ​​like this:

```rust
pub struct Color(String);

impl Color {
    pub fn new(red: u8, green: u8, blue: u8, alpha: Option<u8>) -> Self {
        ...
    }
}
```

**Comment by kennytm** [comment]
it is not this package's job to put assumption on the validity of the color value. 

also your RGBA constructor certainly can't handle wide-gamut colors.

won't fix.
