### ISSUE TITLE
How to export to SVG?

### ISSUE THREAD

**Issue by flosse** [kennytm/qrcode-rust#8]
It would be great to be able to export the QrCode to SVG.
How would that work?

**Comment by kennytm** [comment]
@flosse For now you could draw a square for every bit of the QrCode... We would add this the next version.

**Comment by flosse** [comment]
...ok so extending `Renderer` with a `to_svg_string` function could be a first approach?

**Comment by flosse** [comment]
I got stuck with https://github.com/PistonDevelopers/image/issues/563, so maybe you could answer my question?

**Comment by kennytm** [comment]
0.4 refactored the Renderer structure to support SVG export. See https://github.com/kennytm/qrcode-rust#svg-generation for example.
